version: "3"

includes:
  diff-engine:
    taskfile: workspaces/diff-engine/Taskfile.yml

tasks:
  setup:
    cmds:
      - yarn install

  workspaces:build:
    deps: [setup]
    cmds:
      - yarn wsrun --stages --report --fast-exit --exclude-missing ws:build
    sources:
      - !workspaces/*/build/**/*
    generates:
      - workspaces/diff-engine-wasm/lib/**/*
      - workspaces/diff-engine-wasm/engine/browser/**/*
      - workspaces/diff-engine-wasm/engine/build/**/*
      # - workspace/diff-engine-wasm/engine/target/**/* # do we need this?
      - workspaces/*/build/**/*

  demo:build:
    dir: workspaces/ui
    env:
      PUBLIC_URL: "https://demo.o3c.info"
      CI: "false"
    cmds:
      - yarn build-demo

  spec:build:
    dir: workspaces/ui
    env:
      PUBLIC_URL: "https://apidocs.o3c.info"
      CI: "false"
    cmds:
      - yarn build-spec

  npm:publish:
    deps:
      - workspaces:build
    env:
      OPTIC_SKIP_PREBUILT_INSTALLS: "false"
    cmds:
      - yarn install

  flush-to-disk:
    cmds:
      - sudo /usr/sbin/purge
    status:
      - uname -a | grep -qv Darwin


