version: "3"

tasks:
  setup:
    cmds:
      - yarn install

  workspaces:build:
    deps: [setup]
    cmds:
      - yarn wsrun --stages --report --fast-exit --exclude-missing ws:build
    sources:
      - !workspaces/*/build/**/*
    generates:
      - workspaces/diff-engine-wasm/lib/**/*
      - workspaces/diff-engine-wasm/engine/browser/**/*
      - workspaces/diff-engine-wasm/engine/build/**/*
      # - workspace/diff-engine-wasm/engine/target/**/* # do we need this?
      - workspaces/*/build/**/*

  diff-engine:build:
    deps:
      - diff-engine:add-targets
    cmds:
      - task: diff-engine:build-macos
      - task: diff-engine:build-windows
      - task: diff-engine:build-linux

  diff-engine:build-macos:
    - cargo build --release --workspace --target x86_64-apple-darwin
    - cargo build --release --workspace --target aarch64-apple-darwin

  diff-engine:build-linux:
    env:
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: x86_64-unknown-linux-gnu-gcc
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER: x86_64-linux-musl-gcc
    cmds:
      # - xcode-select --install
      - brew tap SergioBenitez/osxct
      - brew install x86_64-unknown-linux-gnu
      - cargo build --release --workspace --target x86_64-unknown-linux-gnu
      - brew install filosottile/musl-cross/musl-cross
      - cargo build --release --workspace --target x86_64-unknown-linux-musl

  diff-engine:build-windows:
    - brew install mingw-w64
    - cargo build --release --workspace --target x86_64-pc-windows-gnu

  diff-engine:test:
    - cargo tests

  diff-engine:add-targets:
    - rustup target add aarch64-apple-darwin
    - rustup target add x86_64-apple-darwin
    - rustup target add x86_64-unknown-linux-gnu  # glibc
    - rustup target add x86_64-unknown-linux-musl # musl libc
    - rustup target add x86_64-pc-windows-gnu

  diff-engine:macos-build-deps:
    - brew install mingw-64

  demo:build:
    dir: workspaces/ui
    env:
      PUBLIC_URL: "https://demo.o3c.info"
      CI: "false"
    cmds:
      - yarn build-demo

  spec:build:
    dir: workspaces/ui
    env:
      PUBLIC_URL: "https://apidocs.o3c.info"
      CI: "false"
    cmds:
      - yarn build-spec

  npm:publish:
    deps:
      - workspaces:build
    env:
      OPTIC_SKIP_PREBUILT_INSTALLS: "false"
    cmds:
      - yarn install

  flush-disk:
    - sudo /usr/sbin/purge


