version: "3"

tasks:
  build:
    deps:
      - add-targets
    cmds:
      - task: build-macos
      - task: build-windows
      - task: build-linux

  build-macos:
    - cargo build --release --workspace --target x86_64-apple-darwin
    - cargo build --release --workspace --target aarch64-apple-darwin

  build-linux:
    env:
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER: x86_64-unknown-linux-gnu-gcc
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER: x86_64-linux-musl-gcc
    cmds:
      # - xcode-select --install
      - brew tap SergioBenitez/osxct
      - brew install x86_64-unknown-linux-gnu
      - cargo build --release --workspace --target x86_64-unknown-linux-gnu
      - brew install filosottile/musl-cross/musl-cross
      - cargo build --release --workspace --target x86_64-unknown-linux-musl

  build-windows:
    - brew install mingw-w64
    - cargo build --release --workspace --target x86_64-pc-windows-gnu

  test:
    - cargo tests

  add-targets:
    - rustup target add aarch64-apple-darwin
    - rustup target add x86_64-apple-darwin
    - rustup target add x86_64-unknown-linux-gnu  # glibc
    - rustup target add x86_64-unknown-linux-musl # musl libc
    - rustup target add x86_64-pc-windows-gnu
