version: "3"

env:
  REPO: demo
  DOCKER_REGISTRY: 513974440343.dkr.ecr.us-east-1.amazonaws.com

tasks:
  demo:build:
    desc: Build demo site
    deps:
      - :workspaces:clean
    env:
      PUBLIC_URL: "https://demo.o3c.info"
      CI: "false"
    cmds:
      - task: :workspaces:build
      - yarn build-demo

  demo:docker:build:
    desc: Build and package demo site as a Docker container
    deps: ["demo:build"]
    cmds:
      - docker build . -f Dockerfile_demo -t $DOCKER_REGISTRY/$REPO:$TAG

  demo:docker:push:
    - docker push $DOCKER_REGISTRY/$REPO:$TAG

  demo:ci:
    desc: CI workflow
    cmds:
      - task: demo:docker:build
      - task: demo:docker:push
