# this runs on any pr going to release
name: Bump Optic
on:
  pull_request:
    branches:
      - release
    types:
      - opened
      - labeled
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Optic Repository @ Develop
        uses: actions/checkout@28c7f3d2b5162b5ddd3dfd9a45aa55eaf396478b # https://github.com/actions/checkout/commits/v2
        with:
            ref: develop
            token: ${{ github.token }}
      - name: Yarn Install
        run: yarn install
      - name: Extract Label
        run: echo ::set-env name=LABEL::${{ github.event.label.name }}
      - name: Determine version bump type
        run: |
          if [ "$LABEL" = "major" ]; then
            echo ::set-env name=TYPE::major
          elif [ "$LABEL" = "minor" ]; then
            echo ::set-env name=TYPE::minor
          elif [ "$LABEL" = "patch" ]; then
            echo ::set-env name=TYPE::patch
          else
            echo "This label isn't applicable to trigger a version bump"
            exit 1
          fi
      - name: Bump to latest version
        run: yarn bump $TYPE
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        id: cpr
        with:
          branch: bump/bot/${{ github.run_id }}
          base: develop
          commit-message: ${{ env.TYPE }} version bump
          title: ${{ env.TYPE }} version bump
      - name: Comment back with PR
        uses: unsplash/comment-on-pr@master
        env: 
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        with:
          msg: "Bumped version — Approve PR #${{ steps.cpr.outputs.pull-request-number }} to merge the version change"
        