# Releases the latest version of Optic on NPM/Brew/Debian
# Assumes the version has been updated
# Triggers on all changes to the release branch

name: Release

env:
  BUCKET_NAME: optic-packages
  PACKAGE_NAME: api
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on: 
  push:
    branches:
      - release

jobs:
  # Deploys the current version to NPM, and also verifies that the version is correct in the process
  # All Jobs rely on this job because it verifies the version
  release-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: release
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies and Build Optic
      run:  |
        sudo apt-get update
        sudo apt-get install apt-transport-https -y
        echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install sbt -y
        . ./sourceme.sh && optic_build
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.PUBLISH_NPM_OPTIC_BOT }}" > ~/.npmrc
    - run: node ./workspaces/scripts/publish.js
      env:
        OPTIC_PUBLISH_SCOPE: public
  
  # Creates debian package for users to install, hosted on s3
  release-deb:
    needs: release-npm
    runs-on: ubuntu-latest
    steps:
      - run: echo "Debian Release has not been configured yet"
      # - uses: actions/checkout@v2
      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: 12
      # - run: npm ci
      # - name: Install APT Utils
      #   run: sudo apt-get install apt-utils
      # - run: sudo npm i -g @oclif/dev-cli
      # - run: sudo oclif-dev pack:deb
      # - uses: actions/setup-ruby@v1
      #   with:
      #     ruby-version: '2.6'
      # - run: sudo gem install deb-s3
      # - name: Upload to s3
      #   run: sudo deb-s3 upload -e --access-key-id=${{ env.AWS_ACCESS_KEY_ID }} --secret-access-key=${{ env.AWS_SECRET_ACCESS_KEY }} --bucket $BUCKET_NAME --codename ${{ env.PACKAGE_NAME }} --preserve-versions dist/deb/legume_$(npm view ${{ env.PACKAGE_NAME }} version)-1_amd64.deb
  
  # Triggers Homebrew Release - Configure homebrew/core fork repository in the env settings above
  # Requires Repository Access Token (https://github.com/peter-evans/repository-dispatch#token) with repo:write scope
  trigger-brew-release:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1.1.0
        with:
          token: ${{ secrets.HOMEBREW_UTILITY_ACCOUNT }}
          repository: opticdev/homebrew-optic
          event-type: version-update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'