# Releases the latest version of Optic on NPM/Brew/Debian
# Assumes the version has been updated
# Triggers on all changes to the release branch

name: Release

env:
  HOMEBREW_REPO: opticdev/homebrew-optic
  BUCKET_NAME: optic-packages
  PACKAGE_NAME: api
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  REPO_ACCESS_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }} # requires repo:write scope (https://github.com/peter-evans/repository-dispatch#token)

on: 
  push:
    branches:
      - release

jobs:
  # Deploys the current version to NPM, and also verifies that the version is correct in the process
  # All Jobs rely on this job because it verifies the version
  release-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          ref: release
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Install Dependencies and Build Optic
      run:  |
        sudo apt-get update
        sudo apt-get install apt-transport-https -y
        echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
        curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | sudo apt-key add
        sudo apt-get update
        sudo apt-get install sbt -y
        . ./sourceme.sh && optic_build
    - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.PUBLISH_NPM_OPTIC_BOT }}" > ~/.npmrc
    - run: node ./workspaces/scripts/publish.js
      env:
        OPTIC_PUBLISH_SCOPE: public
  
  # Creates debian package for users to install, hosted on s3
  release-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # this part is required for github actions on the site
        with:
          ref: feature/debian-release-flow
      - uses: ./.github/deployDebian/
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: optic-packages
          PACKAGE_NAME: api
          NPM_PACKAGE_NAME: "@useoptic/cli"
          PREFIX_NAME: deb
  
  # Triggers Homebrew Release - Configure homebrew/core fork repository in the env settings above
  # Requires Repository Access Token (https://github.com/peter-evans/repository-dispatch#token) with repo:write scope
  trigger-brew-release:
    needs: release-npm
    runs-on: ubuntu-latest
    steps:
      - run: echo "Brew Release has not been configured yet"
      # - name: Repository Dispatch
      #   uses: peter-evans/repository-dispatch@v1.1.0
      #   with:
      #     token: ${{ env.REPO_ACCESS_TOKEN }}
      #     repository: ${{ env.HOMEBREW_REPO }}
      #     event-type: version-update
      #     client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
