name: Mac OS build host with Task
on:
  push:
    branches:
      - taskfile-blah
jobs:
  build_rust_binaries:
    #runs-on: macos-11.0 # macos-latest doesnt have a new enough xcode to build arm
    # but macos-11.0 is queue hell
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@5a4ac90 # v2.3.4
      - name: Install task
        run: curl -sL https://taskfile.dev/install.sh | sudo bash -s -- -b /usr/local/bin/ # ;)
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: task diff-engine:add-targets
      - run: task diff-engine:build
      - run: task flush-to-disk
      - run: task diff-engine:locate-binaries
