name: Matrix build with Task
on:
  push:
    branches:
      - taskfile
jobs:
  build_rust_binaries:
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        tasks:
          - diff-engine:build-windows
          - diff-engine:build-linux
          - diff-engine:build-macos
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@5a4ac90 # v2.3.4
      - name: Install task
        run: curl -sL https://taskfile.dev/install.sh | sudo bash -s -- -b /usr/local/bin/ # ;)
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: task diff-engine:add-targets
      - name: Build ${{ matrix.os }}
        run: task ${{ matrix.task }}
      - name: Flush to disk
        run: sudo /usr/sbin/purge
        if: runner.os == 'macOS'

      # dispays the binaries we built and their file sizes
      - run: find ./target -perm +111 -type f | grep release/optic_diff | xargs du -shx
