name: Matrix build with Task
on:
  push:
    branches:
      - taskfile
jobs:
  build_rust_binaries:
    strategy:
      matrix:
        platform:
          - os: windows-latest
            task: "diff-engine:build-windows"
          # - os: ubuntu-latest
          #   task: diff-engine:build-linux
          - os: macos-latest
            task: diff-engine:build-macos
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@5a4ac90 # v2.3.4
      - name: Install Task
        uses: Arduino/actions/setup-taskfile@master
        with:
          version: 3.x
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - run: task diff-engine:add-targets
      - name: Build ${{ matrix.platform.os }}
        run: task ${{ matrix.platform.task }}
      - name: Flush to disk
        run: sudo /usr/sbin/purge
        if: runner.os == 'macOS'

      # dispays the binaries we built and their file sizes
      - run: find ./target -perm +111 -type f | grep release/optic_diff | xargs du -shx
