name: Deploy to NPM

on:
  push:
    branches:
     - ronakshah/npm-test

jobs:
  deploy-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm run publish
      env:
        NPM_TOKEN: ${{ secrets.PUBLISH_NPM_OPTIC_BOT }}